package com.ifsc.contacerta.model;

public enum AuditAction {
	TEACHER_CREATED,
	TEACHER_UPDATED,
	TEACHER_ACTIVATED,
	TEACHER_DEACTIVATED,
	INSTITUTION_CREATED,
	INSTITUTION_UPDATED,
	INSTITUTION_ACTIVATED,
	INSTITUTION_DEACTIVATED,
	ROOM_CODE_REGENERATED,
	ROOM_STUDENT_REMOVED,
	EXTRA_ATTEMPT_GRANTED,
	LESSON_PUBLISHED,
	LESSON_ARCHIVED,
	LESSON_ASSIGNMENT_PUBLISHED,
	LESSON_ASSIGNMENT_ARCHIVED,
	ROOM_ARCHIVED,
	VIDEO_PUBLISHED,
	VIDEO_ARCHIVED,
	MATERIAL_PUBLISHED,
	MATERIAL_ARCHIVED,
	QUESTION_ARCHIVED
}
